default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  username: postgres
  password: postgres
  port: 5432
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default